server.port=8080

# Taille max des fichiers uploadés
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Adresse du serveur CORBA (nom du service Docker)
corba.host=corba-server
corba.port=1050
