package PDFServiceModule;


/**
* PDFServiceModule/_PDFServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/pdfcorba/PDFService.idl
* Thursday, May 7, 2026 1:41:51 PM GMT
*/

public class _PDFServiceStub extends org.omg.CORBA.portable.ObjectImpl implements PDFServiceModule.PDFService
{


  // 1. Fusion de plusieurs PDFs en un seul
  public byte[] mergePDFs (byte[][] pdfFiles)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("mergePDFs", true);
                PDFServiceModule.ByteArrayListHelper.write ($out, pdfFiles);
                $in = _invoke ($out);
                byte $result[] = PDFServiceModule.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return mergePDFs (pdfFiles        );
            } finally {
                _releaseReply ($in);
            }
  } // mergePDFs


  // 2. Découpage : retourne une liste de PDFs (1 par page)
  public byte[][] splitPDF (byte[] pdfFile)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("splitPDF", true);
                PDFServiceModule.ByteArrayHelper.write ($out, pdfFile);
                $in = _invoke ($out);
                byte $result[][] = PDFServiceModule.ByteArrayListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return splitPDF (pdfFile        );
            } finally {
                _releaseReply ($in);
            }
  } // splitPDF


  // 3. Extraction de pages spécifiques (ex: "1,3,5")
  public byte[] extractPages (byte[] pdfFile, String pageNumbers)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractPages", true);
                PDFServiceModule.ByteArrayHelper.write ($out, pdfFile);
                $out.write_string (pageNumbers);
                $in = _invoke ($out);
                byte $result[] = PDFServiceModule.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractPages (pdfFile, pageNumbers        );
            } finally {
                _releaseReply ($in);
            }
  } // extractPages


  // 4. Suppression d'une page (numéro commence à 0)
  public byte[] deletePage (byte[] pdfFile, int pageIndex)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deletePage", true);
                PDFServiceModule.ByteArrayHelper.write ($out, pdfFile);
                $out.write_long (pageIndex);
                $in = _invoke ($out);
                byte $result[] = PDFServiceModule.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deletePage (pdfFile, pageIndex        );
            } finally {
                _releaseReply ($in);
            }
  } // deletePage


  // 5. Ajout d'un mot de passe
  public byte[] addPassword (byte[] pdfFile, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addPassword", true);
                PDFServiceModule.ByteArrayHelper.write ($out, pdfFile);
                $out.write_string (password);
                $in = _invoke ($out);
                byte $result[] = PDFServiceModule.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addPassword (pdfFile, password        );
            } finally {
                _releaseReply ($in);
            }
  } // addPassword


  // 6. Conversion PDF -> Images (retourne liste d'images PNG)
  public byte[][] convertToImages (byte[] pdfFile)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("convertToImages", true);
                PDFServiceModule.ByteArrayHelper.write ($out, pdfFile);
                $in = _invoke ($out);
                byte $result[][] = PDFServiceModule.ByteArrayListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return convertToImages (pdfFile        );
            } finally {
                _releaseReply ($in);
            }
  } // convertToImages


  // 7. Extraction du texte brut
  public String extractText (byte[] pdfFile)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractText", true);
                PDFServiceModule.ByteArrayHelper.write ($out, pdfFile);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractText (pdfFile        );
            } finally {
                _releaseReply ($in);
            }
  } // extractText


  // 8. Création d'un PDF à partir d'un texte
  public byte[] createPDF (String content)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPDF", true);
                $out.write_string (content);
                $in = _invoke ($out);
                byte $result[] = PDFServiceModule.ByteArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createPDF (content        );
            } finally {
                _releaseReply ($in);
            }
  } // createPDF

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFServiceModule/PDFService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PDFServiceModule._PDFServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PDFServiceStub
