package PDFServiceModule;


/**
* PDFServiceModule/ByteArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/pdfcorba/PDFService.idl
* Thursday, May 7, 2026 1:41:50 PM GMT
*/


// Type alias pour les octets binaires (contenu des fichiers PDF)
public final class ByteArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public ByteArrayHolder ()
  {
  }

  public ByteArrayHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFServiceModule.ByteArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFServiceModule.ByteArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFServiceModule.ByteArrayHelper.type ();
  }

}
