package PDFServiceModule;

/**
* PDFServiceModule/PDFServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/pdfcorba/PDFService.idl
* Thursday, May 7, 2026 1:41:51 PM GMT
*/

public final class PDFServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFServiceModule.PDFService value = null;

  public PDFServiceHolder ()
  {
  }

  public PDFServiceHolder (PDFServiceModule.PDFService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFServiceModule.PDFServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFServiceModule.PDFServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFServiceModule.PDFServiceHelper.type ();
  }

}
