package PDFServiceModule;


/**
* PDFServiceModule/PDFService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/pdfcorba/PDFService.idl
* Thursday, May 7, 2026 1:41:51 PM GMT
*/

public interface PDFService extends PDFServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PDFService
