package PDFServiceModule;


/**
* PDFServiceModule/PDFServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/com/pdfcorba/PDFService.idl
* Thursday, May 7, 2026 1:41:50 PM GMT
*/

public abstract class PDFServicePOA extends org.omg.PortableServer.Servant
 implements PDFServiceModule.PDFServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("mergePDFs", new java.lang.Integer (0));
    _methods.put ("splitPDF", new java.lang.Integer (1));
    _methods.put ("extractPages", new java.lang.Integer (2));
    _methods.put ("deletePage", new java.lang.Integer (3));
    _methods.put ("addPassword", new java.lang.Integer (4));
    _methods.put ("convertToImages", new java.lang.Integer (5));
    _methods.put ("extractText", new java.lang.Integer (6));
    _methods.put ("createPDF", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // 1. Fusion de plusieurs PDFs en un seul
       case 0:  // PDFServiceModule/PDFService/mergePDFs
       {
         byte pdfFiles[][] = PDFServiceModule.ByteArrayListHelper.read (in);
         byte $result[] = null;
         $result = this.mergePDFs (pdfFiles);
         out = $rh.createReply();
         PDFServiceModule.ByteArrayHelper.write (out, $result);
         break;
       }


  // 2. Découpage : retourne une liste de PDFs (1 par page)
       case 1:  // PDFServiceModule/PDFService/splitPDF
       {
         byte pdfFile[] = PDFServiceModule.ByteArrayHelper.read (in);
         byte $result[][] = null;
         $result = this.splitPDF (pdfFile);
         out = $rh.createReply();
         PDFServiceModule.ByteArrayListHelper.write (out, $result);
         break;
       }


  // 3. Extraction de pages spécifiques (ex: "1,3,5")
       case 2:  // PDFServiceModule/PDFService/extractPages
       {
         byte pdfFile[] = PDFServiceModule.ByteArrayHelper.read (in);
         String pageNumbers = in.read_string ();
         byte $result[] = null;
         $result = this.extractPages (pdfFile, pageNumbers);
         out = $rh.createReply();
         PDFServiceModule.ByteArrayHelper.write (out, $result);
         break;
       }


  // 4. Suppression d'une page (numéro commence à 0)
       case 3:  // PDFServiceModule/PDFService/deletePage
       {
         byte pdfFile[] = PDFServiceModule.ByteArrayHelper.read (in);
         int pageIndex = in.read_long ();
         byte $result[] = null;
         $result = this.deletePage (pdfFile, pageIndex);
         out = $rh.createReply();
         PDFServiceModule.ByteArrayHelper.write (out, $result);
         break;
       }


  // 5. Ajout d'un mot de passe
       case 4:  // PDFServiceModule/PDFService/addPassword
       {
         byte pdfFile[] = PDFServiceModule.ByteArrayHelper.read (in);
         String password = in.read_string ();
         byte $result[] = null;
         $result = this.addPassword (pdfFile, password);
         out = $rh.createReply();
         PDFServiceModule.ByteArrayHelper.write (out, $result);
         break;
       }


  // 6. Conversion PDF -> Images (retourne liste d'images PNG)
       case 5:  // PDFServiceModule/PDFService/convertToImages
       {
         byte pdfFile[] = PDFServiceModule.ByteArrayHelper.read (in);
         byte $result[][] = null;
         $result = this.convertToImages (pdfFile);
         out = $rh.createReply();
         PDFServiceModule.ByteArrayListHelper.write (out, $result);
         break;
       }


  // 7. Extraction du texte brut
       case 6:  // PDFServiceModule/PDFService/extractText
       {
         byte pdfFile[] = PDFServiceModule.ByteArrayHelper.read (in);
         String $result = null;
         $result = this.extractText (pdfFile);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // 8. Création d'un PDF à partir d'un texte
       case 7:  // PDFServiceModule/PDFService/createPDF
       {
         String content = in.read_string ();
         byte $result[] = null;
         $result = this.createPDF (content);
         out = $rh.createReply();
         PDFServiceModule.ByteArrayHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFServiceModule/PDFService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PDFService _this() 
  {
    return PDFServiceHelper.narrow(
    super._this_object());
  }

  public PDFService _this(org.omg.CORBA.ORB orb) 
  {
    return PDFServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PDFServicePOA
